todo:
- create --help option

done:
- bump -m
- write test of killExistingServer
- update dependencies (express)
- update dependencies (liftoff)
- npm module badge
- dependency badge
- kill option
- istanbul
- coveralls
